version: '3.12.3-slim'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: drf_homework
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
  drf_app:
    image: drf_app:latest
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      env_file: "webapp.env"
    networks:
      - backend
  redis:
    image: redis:latest
    networks:
      - backend
  celery:
    image: celery:latest
    command:
      - /bin/sh
      - -c
      - |
        celery -A config worker --loglevel=info
        celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - drf_app
    networks:
      - backend

networks:
  backend:
    driver: bridge

