version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: drf_homework
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    volumes:
      - ./db_data:/var/lib/postgresql/data
  drf_app:
    image: drf_app:latest
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      env_file: "webapp.env"
    networks:
      - backend
      - frontend
  redis:
    image: redis:latest
    networks:
      - backend
  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - drf_app
    networks:
      - backend
  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - drf_app
    networks:
      - backend
networks:
  backend:
    external: false
  frontend:
    driver: bridge

volumes:
  drf_app:
    driver: local
  redis:
    driver: local
  celery_worker:
    driver: local
  celery_beat:
    driver: local
  db_data:
    driver: local