# Generated by Django 5.0.8 on 2024-10-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('stripe_name_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ID от продукта на сайте stripe.com')),
                ('stripe_price_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Изображение Урока')),
                ('video_link', models.URLField(default=None, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ('pk',),
            },
        ),
    ]
