# Generated by Django 5.0.8 on 2024-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(upload_to='lessons/', verbose_name='Изображение Урока'),
        ),
    ]
