# Generated by Django 5.0.8 on 2024-09-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_lesson_preview_alter_lesson_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(default=None, verbose_name='Ссылка на видео'),
        ),
    ]
