# Generated by Django 5.0.8 on 2024-10-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_price_course_stripe_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='stripe_id',
            new_name='stripe_name_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='stripe_price_id',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Ключ на курс'),
        ),
    ]
