# Generated by Django 5.0.8 on 2024-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
